//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordWord
    {
        public int Id { get; set; }
        public string EnglishWord { get; set; }
        public string SpanishWord { get; set; }
        public string SpanishDescription { get; set; }
        public string EnglishDescription { get; set; }
    }
}
