//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASSWORD_LIS_Client.VerificationCodeManagerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailVerificationDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class EmailVerificationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerificationCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerificationCode {
            get {
                return this.VerificationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VerificationCodeField, value) != true)) {
                    this.VerificationCodeField = value;
                    this.RaisePropertyChanged("VerificationCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VerificationCodeManagerServiceReference.IAccountVerificationManager")]
    public interface IAccountVerificationManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountVerificationManager/VerifyEmail", ReplyAction="http://tempuri.org/IAccountVerificationManager/VerifyEmailResponse")]
        bool VerifyEmail(PASSWORD_LIS_Client.VerificationCodeManagerServiceReference.EmailVerificationDTO emailVerificationDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountVerificationManager/VerifyEmail", ReplyAction="http://tempuri.org/IAccountVerificationManager/VerifyEmailResponse")]
        System.Threading.Tasks.Task<bool> VerifyEmailAsync(PASSWORD_LIS_Client.VerificationCodeManagerServiceReference.EmailVerificationDTO emailVerificationDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountVerificationManager/ResendVerificationCode", ReplyAction="http://tempuri.org/IAccountVerificationManager/ResendVerificationCodeResponse")]
        bool ResendVerificationCode(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountVerificationManager/ResendVerificationCode", ReplyAction="http://tempuri.org/IAccountVerificationManager/ResendVerificationCodeResponse")]
        System.Threading.Tasks.Task<bool> ResendVerificationCodeAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountVerificationManagerChannel : PASSWORD_LIS_Client.VerificationCodeManagerServiceReference.IAccountVerificationManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountVerificationManagerClient : System.ServiceModel.ClientBase<PASSWORD_LIS_Client.VerificationCodeManagerServiceReference.IAccountVerificationManager>, PASSWORD_LIS_Client.VerificationCodeManagerServiceReference.IAccountVerificationManager {
        
        public AccountVerificationManagerClient() {
        }
        
        public AccountVerificationManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountVerificationManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountVerificationManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountVerificationManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool VerifyEmail(PASSWORD_LIS_Client.VerificationCodeManagerServiceReference.EmailVerificationDTO emailVerificationDTO) {
            return base.Channel.VerifyEmail(emailVerificationDTO);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyEmailAsync(PASSWORD_LIS_Client.VerificationCodeManagerServiceReference.EmailVerificationDTO emailVerificationDTO) {
            return base.Channel.VerifyEmailAsync(emailVerificationDTO);
        }
        
        public bool ResendVerificationCode(string email) {
            return base.Channel.ResendVerificationCode(email);
        }
        
        public System.Threading.Tasks.Task<bool> ResendVerificationCodeAsync(string email) {
            return base.Channel.ResendVerificationCodeAsync(email);
        }
    }
}
