//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASSWORD_LIS_Client.PasswordResetManagerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordResetDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class PasswordResetDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResetCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword {
            get {
                return this.NewPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.NewPasswordField, value) != true)) {
                    this.NewPasswordField = value;
                    this.RaisePropertyChanged("NewPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResetCode {
            get {
                return this.ResetCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResetCodeField, value) != true)) {
                    this.ResetCodeField = value;
                    this.RaisePropertyChanged("ResetCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class ServiceErrorDetailDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PASSWORD_LIS_Client.PasswordResetManagerServiceReference.ServiceErrorCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PASSWORD_LIS_Client.PasswordResetManagerServiceReference.ServiceErrorCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorCode", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.Enums")]
    public enum ServiceErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USER_ALREADY_EXISTS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DATABASE_ERROR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNEXPECTED_ERROR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STATISTICS_ERROR = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COULD_NOT_CREATE_ROOM = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROOM_NOT_FOUND = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROOM_FULL = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLAYER_NOT_FOUND = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALREADY_IN_ROOM = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_REPORT_PAYLOAD = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORTER_NOT_FOUND = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORTED_PLAYER_NOT_FOUND = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLAYER_ALREADY_BANNED = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAN_PERSISTENCE_ERROR = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUBSCRIPTION_ERROR = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNSUBSCRIPTION_ERROR = 15,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailVerificationDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class EmailVerificationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerificationCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerificationCode {
            get {
                return this.VerificationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VerificationCodeField, value) != true)) {
                    this.VerificationCodeField = value;
                    this.RaisePropertyChanged("VerificationCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PasswordResetManagerServiceReference.IPasswordResetManager")]
    public interface IPasswordResetManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordResetManager/ResetPassword", ReplyAction="http://tempuri.org/IPasswordResetManager/ResetPasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IPasswordResetManager/ResetPasswordServiceErrorDetailDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        bool ResetPassword(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.PasswordResetDTO passwordResetDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordResetManager/ResetPassword", ReplyAction="http://tempuri.org/IPasswordResetManager/ResetPasswordResponse")]
        System.Threading.Tasks.Task<bool> ResetPasswordAsync(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.PasswordResetDTO passwordResetDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordResetManager/RequestPasswordResetCode", ReplyAction="http://tempuri.org/IPasswordResetManager/RequestPasswordResetCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IPasswordResetManager/RequestPasswordResetCodeServiceErrorDeta" +
            "ilDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        bool RequestPasswordResetCode(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.EmailVerificationDTO emailVerificationDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordResetManager/RequestPasswordResetCode", ReplyAction="http://tempuri.org/IPasswordResetManager/RequestPasswordResetCodeResponse")]
        System.Threading.Tasks.Task<bool> RequestPasswordResetCodeAsync(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.EmailVerificationDTO emailVerificationDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordResetManager/ValidatePasswordResetCode", ReplyAction="http://tempuri.org/IPasswordResetManager/ValidatePasswordResetCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IPasswordResetManager/ValidatePasswordResetCodeServiceErrorDet" +
            "ailDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        bool ValidatePasswordResetCode(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.EmailVerificationDTO emailVerificationDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordResetManager/ValidatePasswordResetCode", ReplyAction="http://tempuri.org/IPasswordResetManager/ValidatePasswordResetCodeResponse")]
        System.Threading.Tasks.Task<bool> ValidatePasswordResetCodeAsync(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.EmailVerificationDTO emailVerificationDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPasswordResetManagerChannel : PASSWORD_LIS_Client.PasswordResetManagerServiceReference.IPasswordResetManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PasswordResetManagerClient : System.ServiceModel.ClientBase<PASSWORD_LIS_Client.PasswordResetManagerServiceReference.IPasswordResetManager>, PASSWORD_LIS_Client.PasswordResetManagerServiceReference.IPasswordResetManager {
        
        public PasswordResetManagerClient() {
        }
        
        public PasswordResetManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PasswordResetManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordResetManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordResetManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ResetPassword(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.PasswordResetDTO passwordResetDTO) {
            return base.Channel.ResetPassword(passwordResetDTO);
        }
        
        public System.Threading.Tasks.Task<bool> ResetPasswordAsync(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.PasswordResetDTO passwordResetDTO) {
            return base.Channel.ResetPasswordAsync(passwordResetDTO);
        }
        
        public bool RequestPasswordResetCode(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.EmailVerificationDTO emailVerificationDTO) {
            return base.Channel.RequestPasswordResetCode(emailVerificationDTO);
        }
        
        public System.Threading.Tasks.Task<bool> RequestPasswordResetCodeAsync(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.EmailVerificationDTO emailVerificationDTO) {
            return base.Channel.RequestPasswordResetCodeAsync(emailVerificationDTO);
        }
        
        public bool ValidatePasswordResetCode(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.EmailVerificationDTO emailVerificationDTO) {
            return base.Channel.ValidatePasswordResetCode(emailVerificationDTO);
        }
        
        public System.Threading.Tasks.Task<bool> ValidatePasswordResetCodeAsync(PASSWORD_LIS_Client.PasswordResetManagerServiceReference.EmailVerificationDTO emailVerificationDTO) {
            return base.Channel.ValidatePasswordResetCodeAsync(emailVerificationDTO);
        }
    }
}
