//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASSWORD_LIS_Client.WaitingRoomManagerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class ServiceErrorDetailDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ServiceErrorCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ServiceErrorCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorCode", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.Enums")]
    public enum ServiceErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USER_ALREADY_EXISTS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DATABASE_ERROR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNEXPECTED_ERROR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STATISTICS_ERROR = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COULD_NOT_CREATE_ROOM = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROOM_NOT_FOUND = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROOM_FULL = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLAYER_NOT_FOUND = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALREADY_IN_ROOM = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_REPORT_PAYLOAD = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORTER_NOT_FOUND = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORTED_PLAYER_NOT_FOUND = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLAYER_ALREADY_BANNED = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAN_PERSISTENCE_ERROR = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUBSCRIPTION_ERROR = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNSUBSCRIPTION_ERROR = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL_ARGUMENT = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMAIL_SENDING_ERROR = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMAIL_CONFIGURATION_ERROR = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SECURITY_ERROR = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FORMAT_ERROR = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_OPERATION = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SELF_INVITATION = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MATCH_NOT_FOUND_OR_ENDED = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MATCH_ALREADY_STARTED_OR_FINISHING = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_AUTHORIZED_TO_JOIN = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAX_ONE_REPORT_PER_BAN = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COULD_NOT_CREATE_GAME = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DATA_INTEGRITY_ERROR = 28,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessageDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class ChatMessageDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderNicknameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderNickname {
            get {
                return this.SenderNicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderNicknameField, value) != true)) {
                    this.SenderNicknameField = value;
                    this.RaisePropertyChanged("SenderNickname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class PlayerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhotoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerRole RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.MatchTeam TeamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhotoId {
            get {
                return this.PhotoIdField;
            }
            set {
                if ((this.PhotoIdField.Equals(value) != true)) {
                    this.PhotoIdField = value;
                    this.RaisePropertyChanged("PhotoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerRole Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.MatchTeam Team {
            get {
                return this.TeamField;
            }
            set {
                if ((this.TeamField.Equals(value) != true)) {
                    this.TeamField = value;
                    this.RaisePropertyChanged("Team");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerRole", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.Enums")]
    public enum PlayerRole : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClueGuy = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Guesser = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchTeam", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.Enums")]
    public enum MatchTeam : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BlueTeam = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedTeam = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WaitingRoomManagerServiceReference.IWaitingRoomManager", CallbackContract=typeof(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.IWaitingRoomManagerCallback))]
    public interface IWaitingRoomManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/CreateRoom", ReplyAction="http://tempuri.org/IWaitingRoomManager/CreateRoomResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IWaitingRoomManager/CreateRoomServiceErrorDetailDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        string CreateRoom(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/CreateRoom", ReplyAction="http://tempuri.org/IWaitingRoomManager/CreateRoomResponse")]
        System.Threading.Tasks.Task<string> CreateRoomAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/JoinRoomAsRegisteredPlayer", ReplyAction="http://tempuri.org/IWaitingRoomManager/JoinRoomAsRegisteredPlayerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IWaitingRoomManager/JoinRoomAsRegisteredPlayerServiceErrorDeta" +
            "ilDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        int JoinRoomAsRegisteredPlayer(string gameCode, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/JoinRoomAsRegisteredPlayer", ReplyAction="http://tempuri.org/IWaitingRoomManager/JoinRoomAsRegisteredPlayerResponse")]
        System.Threading.Tasks.Task<int> JoinRoomAsRegisteredPlayerAsync(string gameCode, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/JoinRoomAsGuest", ReplyAction="http://tempuri.org/IWaitingRoomManager/JoinRoomAsGuestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IWaitingRoomManager/JoinRoomAsGuestServiceErrorDetailDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        bool JoinRoomAsGuest(string gameCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/JoinRoomAsGuest", ReplyAction="http://tempuri.org/IWaitingRoomManager/JoinRoomAsGuestResponse")]
        System.Threading.Tasks.Task<bool> JoinRoomAsGuestAsync(string gameCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/SendMessage", ReplyAction="http://tempuri.org/IWaitingRoomManager/SendMessageResponse")]
        void SendMessage(string gameCode, PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessageDTO message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/SendMessage", ReplyAction="http://tempuri.org/IWaitingRoomManager/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string gameCode, PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessageDTO message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/LeaveRoom", ReplyAction="http://tempuri.org/IWaitingRoomManager/LeaveRoomResponse")]
        void LeaveRoom(string gameCode, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/LeaveRoom", ReplyAction="http://tempuri.org/IWaitingRoomManager/LeaveRoomResponse")]
        System.Threading.Tasks.Task LeaveRoomAsync(string gameCode, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/StartGame", ReplyAction="http://tempuri.org/IWaitingRoomManager/StartGameResponse")]
        void StartGame(string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/StartGame", ReplyAction="http://tempuri.org/IWaitingRoomManager/StartGameResponse")]
        System.Threading.Tasks.Task StartGameAsync(string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/GetPlayersInRoom", ReplyAction="http://tempuri.org/IWaitingRoomManager/GetPlayersInRoomResponse")]
        PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO[] GetPlayersInRoom(string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/GetPlayersInRoom", ReplyAction="http://tempuri.org/IWaitingRoomManager/GetPlayersInRoomResponse")]
        System.Threading.Tasks.Task<PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO[]> GetPlayersInRoomAsync(string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/HostLeft", ReplyAction="http://tempuri.org/IWaitingRoomManager/HostLeftResponse")]
        void HostLeft(string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/HostLeft", ReplyAction="http://tempuri.org/IWaitingRoomManager/HostLeftResponse")]
        System.Threading.Tasks.Task HostLeftAsync(string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/SendGameInvitationByEmail", ReplyAction="http://tempuri.org/IWaitingRoomManager/SendGameInvitationByEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IWaitingRoomManager/SendGameInvitationByEmailServiceErrorDetai" +
            "lDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        void SendGameInvitationByEmail(string email, string gameCode, string inviterNickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/SendGameInvitationByEmail", ReplyAction="http://tempuri.org/IWaitingRoomManager/SendGameInvitationByEmailResponse")]
        System.Threading.Tasks.Task SendGameInvitationByEmailAsync(string email, string gameCode, string inviterNickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/SendGameInvitationToFriend", ReplyAction="http://tempuri.org/IWaitingRoomManager/SendGameInvitationToFriendResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IWaitingRoomManager/SendGameInvitationToFriendServiceErrorDeta" +
            "ilDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        void SendGameInvitationToFriend(int friendPlayerId, string gameCode, string inviterNickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/SendGameInvitationToFriend", ReplyAction="http://tempuri.org/IWaitingRoomManager/SendGameInvitationToFriendResponse")]
        System.Threading.Tasks.Task SendGameInvitationToFriendAsync(int friendPlayerId, string gameCode, string inviterNickname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWaitingRoomManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnPlayerJoined")]
        void OnPlayerJoined(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnPlayerLeft")]
        void OnPlayerLeft(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnMessageReceived")]
        void OnMessageReceived(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessageDTO message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnGameStarted")]
        void OnGameStarted();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnHostLeft")]
        void OnHostLeft();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWaitingRoomManagerChannel : PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.IWaitingRoomManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WaitingRoomManagerClient : System.ServiceModel.DuplexClientBase<PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.IWaitingRoomManager>, PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.IWaitingRoomManager {
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string CreateRoom(string email) {
            return base.Channel.CreateRoom(email);
        }
        
        public System.Threading.Tasks.Task<string> CreateRoomAsync(string email) {
            return base.Channel.CreateRoomAsync(email);
        }
        
        public int JoinRoomAsRegisteredPlayer(string gameCode, string email) {
            return base.Channel.JoinRoomAsRegisteredPlayer(gameCode, email);
        }
        
        public System.Threading.Tasks.Task<int> JoinRoomAsRegisteredPlayerAsync(string gameCode, string email) {
            return base.Channel.JoinRoomAsRegisteredPlayerAsync(gameCode, email);
        }
        
        public bool JoinRoomAsGuest(string gameCode, string nickname) {
            return base.Channel.JoinRoomAsGuest(gameCode, nickname);
        }
        
        public System.Threading.Tasks.Task<bool> JoinRoomAsGuestAsync(string gameCode, string nickname) {
            return base.Channel.JoinRoomAsGuestAsync(gameCode, nickname);
        }
        
        public void SendMessage(string gameCode, PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessageDTO message) {
            base.Channel.SendMessage(gameCode, message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string gameCode, PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessageDTO message) {
            return base.Channel.SendMessageAsync(gameCode, message);
        }
        
        public void LeaveRoom(string gameCode, int playerId) {
            base.Channel.LeaveRoom(gameCode, playerId);
        }
        
        public System.Threading.Tasks.Task LeaveRoomAsync(string gameCode, int playerId) {
            return base.Channel.LeaveRoomAsync(gameCode, playerId);
        }
        
        public void StartGame(string gameCode) {
            base.Channel.StartGame(gameCode);
        }
        
        public System.Threading.Tasks.Task StartGameAsync(string gameCode) {
            return base.Channel.StartGameAsync(gameCode);
        }
        
        public PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO[] GetPlayersInRoom(string gameCode) {
            return base.Channel.GetPlayersInRoom(gameCode);
        }
        
        public System.Threading.Tasks.Task<PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO[]> GetPlayersInRoomAsync(string gameCode) {
            return base.Channel.GetPlayersInRoomAsync(gameCode);
        }
        
        public void HostLeft(string gameCode) {
            base.Channel.HostLeft(gameCode);
        }
        
        public System.Threading.Tasks.Task HostLeftAsync(string gameCode) {
            return base.Channel.HostLeftAsync(gameCode);
        }
        
        public void SendGameInvitationByEmail(string email, string gameCode, string inviterNickname) {
            base.Channel.SendGameInvitationByEmail(email, gameCode, inviterNickname);
        }
        
        public System.Threading.Tasks.Task SendGameInvitationByEmailAsync(string email, string gameCode, string inviterNickname) {
            return base.Channel.SendGameInvitationByEmailAsync(email, gameCode, inviterNickname);
        }
        
        public void SendGameInvitationToFriend(int friendPlayerId, string gameCode, string inviterNickname) {
            base.Channel.SendGameInvitationToFriend(friendPlayerId, gameCode, inviterNickname);
        }
        
        public System.Threading.Tasks.Task SendGameInvitationToFriendAsync(int friendPlayerId, string gameCode, string inviterNickname) {
            return base.Channel.SendGameInvitationToFriendAsync(friendPlayerId, gameCode, inviterNickname);
        }
    }
}
