//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASSWORD_LIS_Client.WaitingRoomManagerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessage", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class ChatMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((this.SenderIdField.Equals(value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderUsername {
            get {
                return this.SenderUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderUsernameField, value) != true)) {
                    this.SenderUsernameField = value;
                    this.RaisePropertyChanged("SenderUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class PlayerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReadyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReady {
            get {
                return this.IsReadyField;
            }
            set {
                if ((this.IsReadyField.Equals(value) != true)) {
                    this.IsReadyField = value;
                    this.RaisePropertyChanged("IsReady");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WaitingRoomManagerServiceReference.IWaitingRoomManager", CallbackContract=typeof(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.IWaitingRoomManagerCallback))]
    public interface IWaitingRoomManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/JoinAsRegisteredPlayer", ReplyAction="http://tempuri.org/IWaitingRoomManager/JoinAsRegisteredPlayerResponse")]
        bool JoinAsRegisteredPlayer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/JoinAsRegisteredPlayer", ReplyAction="http://tempuri.org/IWaitingRoomManager/JoinAsRegisteredPlayerResponse")]
        System.Threading.Tasks.Task<bool> JoinAsRegisteredPlayerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/JoinAsGuest", ReplyAction="http://tempuri.org/IWaitingRoomManager/JoinAsGuestResponse")]
        bool JoinAsGuest(string guestUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/JoinAsGuest", ReplyAction="http://tempuri.org/IWaitingRoomManager/JoinAsGuestResponse")]
        System.Threading.Tasks.Task<bool> JoinAsGuestAsync(string guestUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/LeaveRoom", ReplyAction="http://tempuri.org/IWaitingRoomManager/LeaveRoomResponse")]
        void LeaveRoom(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/LeaveRoom", ReplyAction="http://tempuri.org/IWaitingRoomManager/LeaveRoomResponse")]
        System.Threading.Tasks.Task LeaveRoomAsync(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/SendMessage", ReplyAction="http://tempuri.org/IWaitingRoomManager/SendMessageResponse")]
        void SendMessage(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/SendMessage", ReplyAction="http://tempuri.org/IWaitingRoomManager/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/GetConnectedPlayers", ReplyAction="http://tempuri.org/IWaitingRoomManager/GetConnectedPlayersResponse")]
        PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO[] GetConnectedPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/GetConnectedPlayers", ReplyAction="http://tempuri.org/IWaitingRoomManager/GetConnectedPlayersResponse")]
        System.Threading.Tasks.Task<PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO[]> GetConnectedPlayersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWaitingRoomManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnPlayerJoined")]
        void OnPlayerJoined(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnPlayerLeft")]
        void OnPlayerLeft(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnMessageReceived")]
        void OnMessageReceived(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWaitingRoomManagerChannel : PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.IWaitingRoomManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WaitingRoomManagerClient : System.ServiceModel.DuplexClientBase<PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.IWaitingRoomManager>, PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.IWaitingRoomManager {
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool JoinAsRegisteredPlayer(string username) {
            return base.Channel.JoinAsRegisteredPlayer(username);
        }
        
        public System.Threading.Tasks.Task<bool> JoinAsRegisteredPlayerAsync(string username) {
            return base.Channel.JoinAsRegisteredPlayerAsync(username);
        }
        
        public bool JoinAsGuest(string guestUsername) {
            return base.Channel.JoinAsGuest(guestUsername);
        }
        
        public System.Threading.Tasks.Task<bool> JoinAsGuestAsync(string guestUsername) {
            return base.Channel.JoinAsGuestAsync(guestUsername);
        }
        
        public void LeaveRoom(int playerId) {
            base.Channel.LeaveRoom(playerId);
        }
        
        public System.Threading.Tasks.Task LeaveRoomAsync(int playerId) {
            return base.Channel.LeaveRoomAsync(playerId);
        }
        
        public void SendMessage(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessage message) {
            base.Channel.SendMessage(message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessage message) {
            return base.Channel.SendMessageAsync(message);
        }
        
        public PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO[] GetConnectedPlayers() {
            return base.Channel.GetConnectedPlayers();
        }
        
        public System.Threading.Tasks.Task<PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO[]> GetConnectedPlayersAsync() {
            return base.Channel.GetConnectedPlayersAsync();
        }
    }
}
