//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASSWORD_LIS_Client.WaitingRoomManagerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessageDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class ChatMessageDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderNicknameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderNickname {
            get {
                return this.SenderNicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderNicknameField, value) != true)) {
                    this.SenderNicknameField = value;
                    this.RaisePropertyChanged("SenderNickname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class PlayerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhotoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerRole RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.MatchTeam TeamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhotoId {
            get {
                return this.PhotoIdField;
            }
            set {
                if ((this.PhotoIdField.Equals(value) != true)) {
                    this.PhotoIdField = value;
                    this.RaisePropertyChanged("PhotoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerRole Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.MatchTeam Team {
            get {
                return this.TeamField;
            }
            set {
                if ((this.TeamField.Equals(value) != true)) {
                    this.TeamField = value;
                    this.RaisePropertyChanged("Team");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerRole", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.Enums")]
    public enum PlayerRole : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClueGuy = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Guesser = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchTeam", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.Enums")]
    public enum MatchTeam : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BlueTeam = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedTeam = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WaitingRoomManagerServiceReference.IWaitingRoomManager", CallbackContract=typeof(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.IWaitingRoomManagerCallback))]
    public interface IWaitingRoomManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/CreateGame", ReplyAction="http://tempuri.org/IWaitingRoomManager/CreateGameResponse")]
        string CreateGame(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/CreateGame", ReplyAction="http://tempuri.org/IWaitingRoomManager/CreateGameResponse")]
        System.Threading.Tasks.Task<string> CreateGameAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/JoinGameAsRegisteredPlayer", ReplyAction="http://tempuri.org/IWaitingRoomManager/JoinGameAsRegisteredPlayerResponse")]
        bool JoinGameAsRegisteredPlayer(string gameCode, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/JoinGameAsRegisteredPlayer", ReplyAction="http://tempuri.org/IWaitingRoomManager/JoinGameAsRegisteredPlayerResponse")]
        System.Threading.Tasks.Task<bool> JoinGameAsRegisteredPlayerAsync(string gameCode, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/JoinGameAsGuest", ReplyAction="http://tempuri.org/IWaitingRoomManager/JoinGameAsGuestResponse")]
        bool JoinGameAsGuest(string gameCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/JoinGameAsGuest", ReplyAction="http://tempuri.org/IWaitingRoomManager/JoinGameAsGuestResponse")]
        System.Threading.Tasks.Task<bool> JoinGameAsGuestAsync(string gameCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/SendMessage", ReplyAction="http://tempuri.org/IWaitingRoomManager/SendMessageResponse")]
        void SendMessage(string gameCode, PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessageDTO message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/SendMessage", ReplyAction="http://tempuri.org/IWaitingRoomManager/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string gameCode, PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessageDTO message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/LeaveGame", ReplyAction="http://tempuri.org/IWaitingRoomManager/LeaveGameResponse")]
        void LeaveGame(string gameCode, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/LeaveGame", ReplyAction="http://tempuri.org/IWaitingRoomManager/LeaveGameResponse")]
        System.Threading.Tasks.Task LeaveGameAsync(string gameCode, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/StartGame", ReplyAction="http://tempuri.org/IWaitingRoomManager/StartGameResponse")]
        void StartGame(string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/StartGame", ReplyAction="http://tempuri.org/IWaitingRoomManager/StartGameResponse")]
        System.Threading.Tasks.Task StartGameAsync(string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/GetPlayersInGame", ReplyAction="http://tempuri.org/IWaitingRoomManager/GetPlayersInGameResponse")]
        PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO[] GetPlayersInGame(string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaitingRoomManager/GetPlayersInGame", ReplyAction="http://tempuri.org/IWaitingRoomManager/GetPlayersInGameResponse")]
        System.Threading.Tasks.Task<PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO[]> GetPlayersInGameAsync(string gameCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWaitingRoomManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnPlayerJoined")]
        void OnPlayerJoined(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnPlayerLeft")]
        void OnPlayerLeft(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnMessageReceived")]
        void OnMessageReceived(PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessageDTO message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnGameCreated")]
        void OnGameCreated(string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWaitingRoomManager/OnGameStarted")]
        void OnGameStarted();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWaitingRoomManagerChannel : PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.IWaitingRoomManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WaitingRoomManagerClient : System.ServiceModel.DuplexClientBase<PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.IWaitingRoomManager>, PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.IWaitingRoomManager {
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WaitingRoomManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string CreateGame(string email) {
            return base.Channel.CreateGame(email);
        }
        
        public System.Threading.Tasks.Task<string> CreateGameAsync(string email) {
            return base.Channel.CreateGameAsync(email);
        }
        
        public bool JoinGameAsRegisteredPlayer(string gameCode, string email) {
            return base.Channel.JoinGameAsRegisteredPlayer(gameCode, email);
        }
        
        public System.Threading.Tasks.Task<bool> JoinGameAsRegisteredPlayerAsync(string gameCode, string email) {
            return base.Channel.JoinGameAsRegisteredPlayerAsync(gameCode, email);
        }
        
        public bool JoinGameAsGuest(string gameCode, string nickname) {
            return base.Channel.JoinGameAsGuest(gameCode, nickname);
        }
        
        public System.Threading.Tasks.Task<bool> JoinGameAsGuestAsync(string gameCode, string nickname) {
            return base.Channel.JoinGameAsGuestAsync(gameCode, nickname);
        }
        
        public void SendMessage(string gameCode, PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessageDTO message) {
            base.Channel.SendMessage(gameCode, message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string gameCode, PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.ChatMessageDTO message) {
            return base.Channel.SendMessageAsync(gameCode, message);
        }
        
        public void LeaveGame(string gameCode, int playerId) {
            base.Channel.LeaveGame(gameCode, playerId);
        }
        
        public System.Threading.Tasks.Task LeaveGameAsync(string gameCode, int playerId) {
            return base.Channel.LeaveGameAsync(gameCode, playerId);
        }
        
        public void StartGame(string gameCode) {
            base.Channel.StartGame(gameCode);
        }
        
        public System.Threading.Tasks.Task StartGameAsync(string gameCode) {
            return base.Channel.StartGameAsync(gameCode);
        }
        
        public PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO[] GetPlayersInGame(string gameCode) {
            return base.Channel.GetPlayersInGame(gameCode);
        }
        
        public System.Threading.Tasks.Task<PASSWORD_LIS_Client.WaitingRoomManagerServiceReference.PlayerDTO[]> GetPlayersInGameAsync(string gameCode) {
            return base.Channel.GetPlayersInGameAsync(gameCode);
        }
    }
}
