//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASSWORD_LIS_Client.GameManagerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class ServiceErrorDetailDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PASSWORD_LIS_Client.GameManagerServiceReference.ServiceErrorCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PASSWORD_LIS_Client.GameManagerServiceReference.ServiceErrorCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceErrorCode", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.Enums")]
    public enum ServiceErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USER_ALREADY_EXISTS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DATABASE_ERROR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNEXPECTED_ERROR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STATISTICS_ERROR = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COULD_NOT_CREATE_ROOM = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROOM_NOT_FOUND = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROOM_FULL = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLAYER_NOT_FOUND = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALREADY_IN_ROOM = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_REPORT_PAYLOAD = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORTER_NOT_FOUND = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REPORTED_PLAYER_NOT_FOUND = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLAYER_ALREADY_BANNED = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAN_PERSISTENCE_ERROR = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUBSCRIPTION_ERROR = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNSUBSCRIPTION_ERROR = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL_ARGUMENT = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMAIL_SENDING_ERROR = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMAIL_CONFIGURATION_ERROR = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SECURITY_ERROR = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FORMAT_ERROR = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_OPERATION = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SELF_INVITATION = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MATCH_NOT_FOUND_OR_ENDED = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MATCH_ALREADY_STARTED_OR_FINISHING = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_AUTHORIZED_TO_JOIN = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAX_ONE_REPORT_PER_BAN = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COULD_NOT_CREATE_GAME = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DATA_INTEGRITY_ERROR = 28,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationVoteDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class ValidationVoteDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PenalizeMultiwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PenalizeSynonymField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PenalizeMultiword {
            get {
                return this.PenalizeMultiwordField;
            }
            set {
                if ((this.PenalizeMultiwordField.Equals(value) != true)) {
                    this.PenalizeMultiwordField = value;
                    this.RaisePropertyChanged("PenalizeMultiword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PenalizeSynonym {
            get {
                return this.PenalizeSynonymField;
            }
            set {
                if ((this.PenalizeSynonymField.Equals(value) != true)) {
                    this.PenalizeSynonymField = value;
                    this.RaisePropertyChanged("PenalizeSynonym");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnId {
            get {
                return this.TurnIdField;
            }
            set {
                if ((this.TurnIdField.Equals(value) != true)) {
                    this.TurnIdField = value;
                    this.RaisePropertyChanged("TurnId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchInitStateDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class MatchInitStateDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PASSWORD_LIS_Client.GameManagerServiceReference.PlayerDTO> PlayersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PASSWORD_LIS_Client.GameManagerServiceReference.PlayerDTO> Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class PlayerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhotoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PASSWORD_LIS_Client.GameManagerServiceReference.PlayerRole RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PASSWORD_LIS_Client.GameManagerServiceReference.MatchTeam TeamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhotoId {
            get {
                return this.PhotoIdField;
            }
            set {
                if ((this.PhotoIdField.Equals(value) != true)) {
                    this.PhotoIdField = value;
                    this.RaisePropertyChanged("PhotoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PASSWORD_LIS_Client.GameManagerServiceReference.PlayerRole Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PASSWORD_LIS_Client.GameManagerServiceReference.MatchTeam Team {
            get {
                return this.TeamField;
            }
            set {
                if ((this.TeamField.Equals(value) != true)) {
                    this.TeamField = value;
                    this.RaisePropertyChanged("Team");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerRole", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.Enums")]
    public enum PlayerRole : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClueGuy = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Guesser = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchTeam", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.Enums")]
    public enum MatchTeam : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BlueTeam = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedTeam = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoundStartStateDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class RoundStartStateDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentRoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PASSWORD_LIS_Client.GameManagerServiceReference.PlayerDTO> PlayersWithNewRolesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentRound {
            get {
                return this.CurrentRoundField;
            }
            set {
                if ((this.CurrentRoundField.Equals(value) != true)) {
                    this.CurrentRoundField = value;
                    this.RaisePropertyChanged("CurrentRound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PASSWORD_LIS_Client.GameManagerServiceReference.PlayerDTO> PlayersWithNewRoles {
            get {
                return this.PlayersWithNewRolesField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersWithNewRolesField, value) != true)) {
                    this.PlayersWithNewRolesField = value;
                    this.RaisePropertyChanged("PlayersWithNewRoles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordWordDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class PasswordWordDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnglishDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnglishWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpanishDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpanishWordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnglishDescription {
            get {
                return this.EnglishDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EnglishDescriptionField, value) != true)) {
                    this.EnglishDescriptionField = value;
                    this.RaisePropertyChanged("EnglishDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnglishWord {
            get {
                return this.EnglishWordField;
            }
            set {
                if ((object.ReferenceEquals(this.EnglishWordField, value) != true)) {
                    this.EnglishWordField = value;
                    this.RaisePropertyChanged("EnglishWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpanishDescription {
            get {
                return this.SpanishDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SpanishDescriptionField, value) != true)) {
                    this.SpanishDescriptionField = value;
                    this.RaisePropertyChanged("SpanishDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpanishWord {
            get {
                return this.SpanishWordField;
            }
            set {
                if ((object.ReferenceEquals(this.SpanishWordField, value) != true)) {
                    this.SpanishWordField = value;
                    this.RaisePropertyChanged("SpanishWord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuessResultDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class GuessResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PASSWORD_LIS_Client.GameManagerServiceReference.MatchTeam TeamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCorrect {
            get {
                return this.IsCorrectField;
            }
            set {
                if ((this.IsCorrectField.Equals(value) != true)) {
                    this.IsCorrectField = value;
                    this.RaisePropertyChanged("IsCorrect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewScore {
            get {
                return this.NewScoreField;
            }
            set {
                if ((this.NewScoreField.Equals(value) != true)) {
                    this.NewScoreField = value;
                    this.RaisePropertyChanged("NewScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PASSWORD_LIS_Client.GameManagerServiceReference.MatchTeam Team {
            get {
                return this.TeamField;
            }
            set {
                if ((this.TeamField.Equals(value) != true)) {
                    this.TeamField = value;
                    this.RaisePropertyChanged("Team");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TurnHistoryDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class TurnHistoryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClueUsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PASSWORD_LIS_Client.GameManagerServiceReference.PasswordWordDTO PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClueUsed {
            get {
                return this.ClueUsedField;
            }
            set {
                if ((object.ReferenceEquals(this.ClueUsedField, value) != true)) {
                    this.ClueUsedField = value;
                    this.RaisePropertyChanged("ClueUsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PASSWORD_LIS_Client.GameManagerServiceReference.PasswordWordDTO Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnId {
            get {
                return this.TurnIdField;
            }
            set {
                if ((this.TurnIdField.Equals(value) != true)) {
                    this.TurnIdField = value;
                    this.RaisePropertyChanged("TurnId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResultDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class ValidationResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewBlueTeamScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewRedTeamScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PASSWORD_LIS_Client.GameManagerServiceReference.MatchTeam TeamThatWasValidatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPenaltyAppliedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewBlueTeamScore {
            get {
                return this.NewBlueTeamScoreField;
            }
            set {
                if ((this.NewBlueTeamScoreField.Equals(value) != true)) {
                    this.NewBlueTeamScoreField = value;
                    this.RaisePropertyChanged("NewBlueTeamScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewRedTeamScore {
            get {
                return this.NewRedTeamScoreField;
            }
            set {
                if ((this.NewRedTeamScoreField.Equals(value) != true)) {
                    this.NewRedTeamScoreField = value;
                    this.RaisePropertyChanged("NewRedTeamScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PASSWORD_LIS_Client.GameManagerServiceReference.MatchTeam TeamThatWasValidated {
            get {
                return this.TeamThatWasValidatedField;
            }
            set {
                if ((this.TeamThatWasValidatedField.Equals(value) != true)) {
                    this.TeamThatWasValidatedField = value;
                    this.RaisePropertyChanged("TeamThatWasValidated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPenaltyApplied {
            get {
                return this.TotalPenaltyAppliedField;
            }
            set {
                if ((this.TotalPenaltyAppliedField.Equals(value) != true)) {
                    this.TotalPenaltyAppliedField = value;
                    this.RaisePropertyChanged("TotalPenaltyApplied");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchSummaryDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class MatchSummaryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BlueScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RedScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<PASSWORD_LIS_Client.GameManagerServiceReference.MatchTeam> WinnerTeamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlueScore {
            get {
                return this.BlueScoreField;
            }
            set {
                if ((this.BlueScoreField.Equals(value) != true)) {
                    this.BlueScoreField = value;
                    this.RaisePropertyChanged("BlueScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RedScore {
            get {
                return this.RedScoreField;
            }
            set {
                if ((this.RedScoreField.Equals(value) != true)) {
                    this.RedScoreField = value;
                    this.RaisePropertyChanged("RedScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<PASSWORD_LIS_Client.GameManagerServiceReference.MatchTeam> WinnerTeam {
            get {
                return this.WinnerTeamField;
            }
            set {
                if ((this.WinnerTeamField.Equals(value) != true)) {
                    this.WinnerTeamField = value;
                    this.RaisePropertyChanged("WinnerTeam");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameManagerServiceReference.IGameManager", CallbackContract=typeof(PASSWORD_LIS_Client.GameManagerServiceReference.IGameManagerCallback))]
    public interface IGameManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/SubscribeToMatch", ReplyAction="http://tempuri.org/IGameManager/SubscribeToMatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.GameManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IGameManager/SubscribeToMatchServiceErrorDetailDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        void SubscribeToMatch(string gameCode, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/SubscribeToMatch", ReplyAction="http://tempuri.org/IGameManager/SubscribeToMatchResponse")]
        System.Threading.Tasks.Task SubscribeToMatchAsync(string gameCode, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/SubmitClue", ReplyAction="http://tempuri.org/IGameManager/SubmitClueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.GameManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IGameManager/SubmitClueServiceErrorDetailDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        void SubmitClue(string gameCode, int senderPlayerId, string clue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/SubmitClue", ReplyAction="http://tempuri.org/IGameManager/SubmitClueResponse")]
        System.Threading.Tasks.Task SubmitClueAsync(string gameCode, int senderPlayerId, string clue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/SubmitGuess", ReplyAction="http://tempuri.org/IGameManager/SubmitGuessResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.GameManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IGameManager/SubmitGuessServiceErrorDetailDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        void SubmitGuess(string gameCode, int senderPlayerId, string guess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/SubmitGuess", ReplyAction="http://tempuri.org/IGameManager/SubmitGuessResponse")]
        System.Threading.Tasks.Task SubmitGuessAsync(string gameCode, int senderPlayerId, string guess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/PassTurn", ReplyAction="http://tempuri.org/IGameManager/PassTurnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.GameManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IGameManager/PassTurnServiceErrorDetailDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        void PassTurn(string gameCode, int senderPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/PassTurn", ReplyAction="http://tempuri.org/IGameManager/PassTurnResponse")]
        System.Threading.Tasks.Task PassTurnAsync(string gameCode, int senderPlayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/SubmitValidationVotes", ReplyAction="http://tempuri.org/IGameManager/SubmitValidationVotesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PASSWORD_LIS_Client.GameManagerServiceReference.ServiceErrorDetailDTO), Action="http://tempuri.org/IGameManager/SubmitValidationVotesServiceErrorDetailDTOFault", Name="ServiceErrorDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.Contracts.DTOs")]
        void SubmitValidationVotes(string gameCode, int senderPlayerId, System.Collections.Generic.List<PASSWORD_LIS_Client.GameManagerServiceReference.ValidationVoteDTO> votes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/SubmitValidationVotes", ReplyAction="http://tempuri.org/IGameManager/SubmitValidationVotesResponse")]
        System.Threading.Tasks.Task SubmitValidationVotesAsync(string gameCode, int senderPlayerId, System.Collections.Generic.List<PASSWORD_LIS_Client.GameManagerServiceReference.ValidationVoteDTO> votes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnMatchInitialized")]
        void OnMatchInitialized(PASSWORD_LIS_Client.GameManagerServiceReference.MatchInitStateDTO state);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnNewRoundStarted")]
        void OnNewRoundStarted(PASSWORD_LIS_Client.GameManagerServiceReference.RoundStartStateDTO state);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnTimerTick")]
        void OnTimerTick(int secondsLeft);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnNewPassword")]
        void OnNewPassword(PASSWORD_LIS_Client.GameManagerServiceReference.PasswordWordDTO password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnClueReceived")]
        void OnClueReceived(string clue);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnGuessResult")]
        void OnGuessResult(PASSWORD_LIS_Client.GameManagerServiceReference.GuessResultDTO result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnBeginRoundValidation")]
        void OnBeginRoundValidation(System.Collections.Generic.List<PASSWORD_LIS_Client.GameManagerServiceReference.TurnHistoryDTO> turns);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnValidationTimerTick")]
        void OnValidationTimerTick(int secondsLeft);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnValidationComplete")]
        void OnValidationComplete(PASSWORD_LIS_Client.GameManagerServiceReference.ValidationResultDTO result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnSuddenDeathStarted")]
        void OnSuddenDeathStarted();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnMatchOver")]
        void OnMatchOver(PASSWORD_LIS_Client.GameManagerServiceReference.MatchSummaryDTO summary);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnMatchCancelled")]
        void OnMatchCancelled(string reason);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameManagerChannel : PASSWORD_LIS_Client.GameManagerServiceReference.IGameManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameManagerClient : System.ServiceModel.DuplexClientBase<PASSWORD_LIS_Client.GameManagerServiceReference.IGameManager>, PASSWORD_LIS_Client.GameManagerServiceReference.IGameManager {
        
        public GameManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SubscribeToMatch(string gameCode, int playerId) {
            base.Channel.SubscribeToMatch(gameCode, playerId);
        }
        
        public System.Threading.Tasks.Task SubscribeToMatchAsync(string gameCode, int playerId) {
            return base.Channel.SubscribeToMatchAsync(gameCode, playerId);
        }
        
        public void SubmitClue(string gameCode, int senderPlayerId, string clue) {
            base.Channel.SubmitClue(gameCode, senderPlayerId, clue);
        }
        
        public System.Threading.Tasks.Task SubmitClueAsync(string gameCode, int senderPlayerId, string clue) {
            return base.Channel.SubmitClueAsync(gameCode, senderPlayerId, clue);
        }
        
        public void SubmitGuess(string gameCode, int senderPlayerId, string guess) {
            base.Channel.SubmitGuess(gameCode, senderPlayerId, guess);
        }
        
        public System.Threading.Tasks.Task SubmitGuessAsync(string gameCode, int senderPlayerId, string guess) {
            return base.Channel.SubmitGuessAsync(gameCode, senderPlayerId, guess);
        }
        
        public void PassTurn(string gameCode, int senderPlayerId) {
            base.Channel.PassTurn(gameCode, senderPlayerId);
        }
        
        public System.Threading.Tasks.Task PassTurnAsync(string gameCode, int senderPlayerId) {
            return base.Channel.PassTurnAsync(gameCode, senderPlayerId);
        }
        
        public void SubmitValidationVotes(string gameCode, int senderPlayerId, System.Collections.Generic.List<PASSWORD_LIS_Client.GameManagerServiceReference.ValidationVoteDTO> votes) {
            base.Channel.SubmitValidationVotes(gameCode, senderPlayerId, votes);
        }
        
        public System.Threading.Tasks.Task SubmitValidationVotesAsync(string gameCode, int senderPlayerId, System.Collections.Generic.List<PASSWORD_LIS_Client.GameManagerServiceReference.ValidationVoteDTO> votes) {
            return base.Channel.SubmitValidationVotesAsync(gameCode, senderPlayerId, votes);
        }
    }
}
