//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int RequesterId { get; set; }
        public int AddresseeId { get; set; }
        public int Status { get; set; }
        public System.DateTime RequestedAt { get; set; }
        public Nullable<System.DateTime> RespondedAt { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
