//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialAccount
    {
        public int Id { get; set; }
        public int UserAccountId { get; set; }
        public string Provider { get; set; }
        public string Username { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
