//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASSWORD_LIS_Client.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PASSWORD_LIS_Client.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already have an Account?.
        /// </summary>
        internal static string alreadyHaveAccountText {
            get {
                return ResourceManager.GetString("alreadyHaveAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to Lobby.
        /// </summary>
        internal static string backToLobbyText {
            get {
                return ResourceManager.GetString("backToLobbyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blue Team.
        /// </summary>
        internal static string blueTeamText {
            get {
                return ResourceManager.GetString("blueTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changes Saved Succesfully.
        /// </summary>
        internal static string changedSavedText {
            get {
                return ResourceManager.GetString("changedSavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        internal static string changePasswordText {
            get {
                return ResourceManager.GetString("changePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clue.
        /// </summary>
        internal static string clueText {
            get {
                return ResourceManager.GetString("clueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A confirmation code will be sent to the registered e-mail address to activate the account.
        /// </summary>
        internal static string codeActivationMessageText {
            get {
                return ResourceManager.GetString("codeActivationMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code:.
        /// </summary>
        internal static string codeWordText {
            get {
                return ResourceManager.GetString("codeWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        internal static string confirmUserPasswordText {
            get {
                return ResourceManager.GetString("confirmUserPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up for Free.
        /// </summary>
        internal static string createAccountText {
            get {
                return ResourceManager.GetString("createAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Round 1 of 3.
        /// </summary>
        internal static string currentRoundText {
            get {
                return ResourceManager.GetString("currentRoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Word 2 of 5.
        /// </summary>
        internal static string currentWordText {
            get {
                return ResourceManager.GetString("currentWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type your e-mail to reset your password.
        /// </summary>
        internal static string emailRetrievePasswordText {
            get {
                return ResourceManager.GetString("emailRetrievePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        internal static string emailText {
            get {
                return ResourceManager.GetString("emailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a Match Code to Join.
        /// </summary>
        internal static string enterCodeToJoinText {
            get {
                return ResourceManager.GetString("enterCodeToJoinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot Password.
        /// </summary>
        internal static string forgotUserPasswordText {
            get {
                return ResourceManager.GetString("forgotUserPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends List.
        /// </summary>
        internal static string friendsListText {
            get {
                return ResourceManager.GetString("friendsListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group Chat.
        /// </summary>
        internal static string groupChatText {
            get {
                return ResourceManager.GetString("groupChatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try to guess the PASSWORD with!.
        /// </summary>
        internal static string guessPasswordWithText {
            get {
                return ResourceManager.GetString("guessPasswordWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How to Play?.
        /// </summary>
        internal static string howToPlayText {
            get {
                return ResourceManager.GetString("howToPlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The E-mail isn&apos;t valid.
        /// </summary>
        internal static string invalidEmailErrorText {
            get {
                return ResourceManager.GetString("invalidEmailErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation by Mail.
        /// </summary>
        internal static string invitationMailText {
            get {
                return ResourceManager.GetString("invitationMailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite your Friends.
        /// </summary>
        internal static string inviteYourFriendsText {
            get {
                return ResourceManager.GetString("inviteYourFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Game.
        /// </summary>
        internal static string joingGameText {
            get {
                return ResourceManager.GetString("joingGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        internal static string lastNameText {
            get {
                return ResourceManager.GetString("lastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        internal static string logInText {
            get {
                return ResourceManager.GetString("logInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        internal static string logOutText {
            get {
                return ResourceManager.GetString("logOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good luck next time!.
        /// </summary>
        internal static string loosersMessageText {
            get {
                return ResourceManager.GetString("loosersMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loosers.
        /// </summary>
        internal static string loosersText {
            get {
                return ResourceManager.GetString("loosersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify that both passwords match.
        /// </summary>
        internal static string matchingPasswordErrorText {
            get {
                return ResourceManager.GetString("matchingPasswordErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music.
        /// </summary>
        internal static string musicText {
            get {
                return ResourceManager.GetString("musicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name.
        /// </summary>
        internal static string nameText {
            get {
                return ResourceManager.GetString("nameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nextRound.
        /// </summary>
        internal static string nextRoundText {
            get {
                return ResourceManager.GetString("nextRoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname.
        /// </summary>
        internal static string nicknameText {
            get {
                return ResourceManager.GetString("nicknameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don&apos;t have an Account?.
        /// </summary>
        internal static string noAccountText {
            get {
                return ResourceManager.GetString("noAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Was more than one word given as a clue?.
        /// </summary>
        internal static string oneMoreWordQuestionText {
            get {
                return ResourceManager.GetString("oneMoreWordQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pass.
        /// </summary>
        internal static string passText {
            get {
                return ResourceManager.GetString("passText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The PASSWORD to guess is:.
        /// </summary>
        internal static string passwordToGuessText {
            get {
                return ResourceManager.GetString("passwordToGuessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play Again.
        /// </summary>
        internal static string playAgainText {
            get {
                return ResourceManager.GetString("playAgainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        internal static string playersText {
            get {
                return ResourceManager.GetString("playersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        internal static string playText {
            get {
                return ResourceManager.GetString("playText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        internal static string profileText {
            get {
                return ResourceManager.GetString("profileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red Team.
        /// </summary>
        internal static string redTeamText {
            get {
                return ResourceManager.GetString("redTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please complete the required fields.
        /// </summary>
        internal static string requiredFieldsText {
            get {
                return ResourceManager.GetString("requiredFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retrieve Password.
        /// </summary>
        internal static string retrieveUserPasswordText {
            get {
                return ResourceManager.GetString("retrieveUserPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Round Validation.
        /// </summary>
        internal static string roundValidationText {
            get {
                return ResourceManager.GetString("roundValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Each game will consist of two teams of two members.
        ///The teams will be made up of a &quot;Clue Guy,&quot; who will be the player who will see the current password and will be responsible for giving one word per turn as a clue, and a &quot;Guesser,&quot; who will be responsible for guessing the secret word based on the clues given by the other player.
        ///Each game will consist of five rounds of one minute each, with five passwords that the &quot;Guesser&quot; will have to guess.
        ///Each password correctly guessed will be worth one point for  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string rulesGameText {
            get {
                return ResourceManager.GetString("rulesGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        internal static string saveChangesText {
            get {
                return ResourceManager.GetString("saveChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score.
        /// </summary>
        internal static string scoreTopText {
            get {
                return ResourceManager.GetString("scoreTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose an Avatar.
        /// </summary>
        internal static string selectAvatarText {
            get {
                return ResourceManager.GetString("selectAvatarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Code.
        /// </summary>
        internal static string sendCodeText {
            get {
                return ResourceManager.GetString("sendCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Invitation.
        /// </summary>
        internal static string sendInvitationText {
            get {
                return ResourceManager.GetString("sendInvitationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        internal static string sendText {
            get {
                return ResourceManager.GetString("sendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string settingsText {
            get {
                return ResourceManager.GetString("settingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error registering user. Please try again later.
        /// </summary>
        internal static string signUpErrorText {
            get {
                return ResourceManager.GetString("signUpErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        internal static string signUpText {
            get {
                return ResourceManager.GetString("signUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Were synonyms used?.
        /// </summary>
        internal static string sinonymsQuestionText {
            get {
                return ResourceManager.GetString("sinonymsQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social Media.
        /// </summary>
        internal static string socialMediaText {
            get {
                return ResourceManager.GetString("socialMediaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound Effects.
        /// </summary>
        internal static string soundEffectsText {
            get {
                return ResourceManager.GetString("soundEffectsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Game.
        /// </summary>
        internal static string startGameText {
            get {
                return ResourceManager.GetString("startGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful Login.
        /// </summary>
        internal static string successfulLoginText {
            get {
                return ResourceManager.GetString("successfulLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful PASSWORDS:.
        /// </summary>
        internal static string successfulPasswordsText {
            get {
                return ResourceManager.GetString("successfulPasswordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration Successful.
        /// </summary>
        internal static string successfulSignUpText {
            get {
                return ResourceManager.GetString("successfulSignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a By Signing Up you Agree to our Terms &amp; Conditions.
        /// </summary>
        internal static string termsAndConditionsText {
            get {
                return ResourceManager.GetString("termsAndConditionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Players.
        /// </summary>
        internal static string topPlayersText {
            get {
                return ResourceManager.GetString("topPlayersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type your New Password.
        /// </summary>
        internal static string typePasswordText {
            get {
                return ResourceManager.GetString("typePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User already exist with that e-mail.
        /// </summary>
        internal static string userAlreadyExistText {
            get {
                return ResourceManager.GetString("userAlreadyExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string userPasswordText {
            get {
                return ResourceManager.GetString("userPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use 8-15 characters including at least one uppercase, one lowercase, one numeric character and one symbol.
        /// </summary>
        internal static string usserPasswordRequirementsText {
            get {
                return ResourceManager.GetString("usserPasswordRequirementsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate Round.
        /// </summary>
        internal static string validateRoundText {
            get {
                return ResourceManager.GetString("validateRoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type the 4 digit code sent to the e-mail:.
        /// </summary>
        internal static string verifyCodeMessageText {
            get {
                return ResourceManager.GetString("verifyCodeMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Didn&apos;t receive the code?.
        /// </summary>
        internal static string verifyCodeNotSendText {
            get {
                return ResourceManager.GetString("verifyCodeNotSendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend Code.
        /// </summary>
        internal static string verifyCodeResendCodeText {
            get {
                return ResourceManager.GetString("verifyCodeResendCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Code.
        /// </summary>
        internal static string verifyCodeText {
            get {
                return ResourceManager.GetString("verifyCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Congratulations you won PASSWORD.
        /// </summary>
        internal static string winnersMessageText {
            get {
                return ResourceManager.GetString("winnersMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Winners.
        /// </summary>
        internal static string winnersText {
            get {
                return ResourceManager.GetString("winnersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write a clue for your teammate:.
        /// </summary>
        internal static string writeClueText {
            get {
                return ResourceManager.GetString("writeClueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your friend&apos;s email address to invite:.
        /// </summary>
        internal static string writeEmailToInviteText {
            get {
                return ResourceManager.GetString("writeEmailToInviteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the PASSWORD that you think is.
        /// </summary>
        internal static string writePasswordText {
            get {
                return ResourceManager.GetString("writePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect e-mail or password.
        /// </summary>
        internal static string wrongCredentialsText {
            get {
                return ResourceManager.GetString("wrongCredentialsText", resourceCulture);
            }
        }
    }
}
