//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASSWORD_LIS_Client.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PASSWORD_LIS_Client.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string acceptText {
            get {
                return ResourceManager.GetString("acceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Friend.
        /// </summary>
        public static string addFriendTitleText {
            get {
                return ResourceManager.GetString("addFriendTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a friend request, or you are already friends with this player.
        /// </summary>
        public static string alreadyFriendsText {
            get {
                return ResourceManager.GetString("alreadyFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already have an Account?.
        /// </summary>
        public static string alreadyHaveAccountText {
            get {
                return ResourceManager.GetString("alreadyHaveAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to Lobby.
        /// </summary>
        public static string backToLobbyText {
            get {
                return ResourceManager.GetString("backToLobbyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Suspended.
        /// </summary>
        public static string bannedAccountText {
            get {
                return ResourceManager.GetString("bannedAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have accumulated 3 reports and your account has been suspended for 1 hour. You will be kicked out of the room. You have been suspended..
        /// </summary>
        public static string bannedMessageText {
            get {
                return ResourceManager.GetString("bannedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been suspended..
        /// </summary>
        public static string bannedText {
            get {
                return ResourceManager.GetString("bannedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blue Team.
        /// </summary>
        public static string blueTeamText {
            get {
                return ResourceManager.GetString("blueTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot create games; your account is temporarily suspended..
        /// </summary>
        public static string cantCreateMatchText {
            get {
                return ResourceManager.GetString("cantCreateMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot join games; your account is temporarily suspended..
        /// </summary>
        public static string cantJoinMatchText {
            get {
                return ResourceManager.GetString("cantJoinMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not report yourself.
        /// </summary>
        public static string cantReportYourself {
            get {
                return ResourceManager.GetString("cantReportYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changes Saved Succesfully.
        /// </summary>
        public static string changedSavedText {
            get {
                return ResourceManager.GetString("changedSavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string changePasswordText {
            get {
                return ResourceManager.GetString("changePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not save changes to the server..
        /// </summary>
        public static string changesSavedErrorText {
            get {
                return ResourceManager.GetString("changesSavedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clue Guy.
        /// </summary>
        public static string clueGuyText {
            get {
                return ResourceManager.GetString("clueGuyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clue.
        /// </summary>
        public static string clueText {
            get {
                return ResourceManager.GetString("clueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A confirmation code will be sent to the registered e-mail address to activate the account.
        /// </summary>
        public static string codeActivationMessageText {
            get {
                return ResourceManager.GetString("codeActivationMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The code is incorrect or has expired..
        /// </summary>
        public static string codeIncorrectOrExpiredText {
            get {
                return ResourceManager.GetString("codeIncorrectOrExpiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not send the code. Verify that the email is correct or wait a minute before retrying..
        /// </summary>
        public static string codeSendFailedText {
            get {
                return ResourceManager.GetString("codeSendFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code Sent.
        /// </summary>
        public static string codeSentTitleText {
            get {
                return ResourceManager.GetString("codeSentTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code:.
        /// </summary>
        public static string codeWordText {
            get {
                return ResourceManager.GetString("codeWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        public static string confirmUserPasswordText {
            get {
                return ResourceManager.GetString("confirmUserPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection error when attempting to remove friend.
        /// </summary>
        public static string connectionErrorAtRemovingFriendText {
            get {
                return ResourceManager.GetString("connectionErrorAtRemovingFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection Error.
        /// </summary>
        public static string connectionErrorTitleText {
            get {
                return ResourceManager.GetString("connectionErrorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code copied to clipboard!.
        /// </summary>
        public static string copiedToClipboardText {
            get {
                return ResourceManager.GetString("copiedToClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy Code.
        /// </summary>
        public static string copyCodeText {
            get {
                return ResourceManager.GetString("copyCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game could not be created..
        /// </summary>
        public static string couldNotCreateMatch {
            get {
                return ResourceManager.GetString("couldNotCreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not join the room.
        /// </summary>
        public static string couldNotJoinText {
            get {
                return ResourceManager.GetString("couldNotJoinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The friends list could not be loaded.
        /// </summary>
        public static string couldNotLoadFriendsText {
            get {
                return ResourceManager.GetString("couldNotLoadFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The friend could not be removed.
        /// </summary>
        public static string couldNotRemoveFriendTitleText {
            get {
                return ResourceManager.GetString("couldNotRemoveFriendTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The friend request could not be sent.
        /// </summary>
        public static string couldNotSentRequestText {
            get {
                return ResourceManager.GetString("couldNotSentRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The report could not be sent..
        /// </summary>
        public static string couldNotSummitReportText {
            get {
                return ResourceManager.GetString("couldNotSummitReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up for Free.
        /// </summary>
        public static string createAccountText {
            get {
                return ResourceManager.GetString("createAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Critical Error.
        /// </summary>
        public static string criticalErrorTitle {
            get {
                return ResourceManager.GetString("criticalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current reports:.
        /// </summary>
        public static string currentReportsText {
            get {
                return ResourceManager.GetString("currentReportsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Round: {0} of 5.
        /// </summary>
        public static string currentRoundText {
            get {
                return ResourceManager.GetString("currentRoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Word: {0} of 5.
        /// </summary>
        public static string currentWordText {
            get {
                return ResourceManager.GetString("currentWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to remove {0}  from your friends list?.
        /// </summary>
        public static string deletionConfirmationText {
            get {
                return ResourceManager.GetString("deletionConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm deletion.
        /// </summary>
        public static string deletionConfirmationTitleText {
            get {
                return ResourceManager.GetString("deletionConfirmationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type your e-mail to reset your password.
        /// </summary>
        public static string emailRetrievePasswordText {
            get {
                return ResourceManager.GetString("emailRetrievePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        public static string emailText {
            get {
                return ResourceManager.GetString("emailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name cannot be empty.
        /// </summary>
        public static string emptyFirstNameText {
            get {
                return ResourceManager.GetString("emptyFirstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name cannot be empty.
        /// </summary>
        public static string emptyLastNameText {
            get {
                return ResourceManager.GetString("emptyLastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname cannot be empty.
        /// </summary>
        public static string emptyNicknameText {
            get {
                return ResourceManager.GetString("emptyNicknameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a Match Code to Join.
        /// </summary>
        public static string enterCodeToJoinText {
            get {
                return ResourceManager.GetString("enterCodeToJoinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your friend&apos;s email to add them.
        /// </summary>
        public static string enterFriendEmailToAddText {
            get {
                return ResourceManager.GetString("enterFriendEmailToAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string errorTitleText {
            get {
                return ResourceManager.GetString("errorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The friend request could not be sent because you have already sent a request to that player.
        /// </summary>
        public static string existingFriendRequestText {
            get {
                return ResourceManager.GetString("existingFriendRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The friend request could not be sent because you are already friends with that player.
        /// </summary>
        public static string existingFriendshipText {
            get {
                return ResourceManager.GetString("existingFriendshipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name cannot exceed 50 characters..
        /// </summary>
        public static string firstNameTooLongText {
            get {
                return ResourceManager.GetString("firstNameTooLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot Password.
        /// </summary>
        public static string forgotUserPasswordText {
            get {
                return ResourceManager.GetString("forgotUserPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This player has already sent you a friend request, check your inbox.
        /// </summary>
        public static string friendRequestInboxText {
            get {
                return ResourceManager.GetString("friendRequestInboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Requests.
        /// </summary>
        public static string friendRequestsTitleText {
            get {
                return ResourceManager.GetString("friendRequestsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot send a friend request to yourself.
        /// </summary>
        public static string friendRequestToYourselfText {
            get {
                return ResourceManager.GetString("friendRequestToYourselfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends List.
        /// </summary>
        public static string friendsListText {
            get {
                return ResourceManager.GetString("friendsListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group Chat.
        /// </summary>
        public static string groupChatText {
            get {
                return ResourceManager.GetString("groupChatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guesser:.
        /// </summary>
        public static string guesserText {
            get {
                return ResourceManager.GetString("guesserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try to guess the PASSWORD with!.
        /// </summary>
        public static string guessPasswordWithText {
            get {
                return ResourceManager.GetString("guessPasswordWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guests can not report players.
        /// </summary>
        public static string guestCantReportText {
            get {
                return ResourceManager.GetString("guestCantReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string guestText {
            get {
                return ResourceManager.GetString("guestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The host has left the room. The game has been canceled..
        /// </summary>
        public static string hostLeftText {
            get {
                return ResourceManager.GetString("hostLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host left the game.
        /// </summary>
        public static string hostLeftTitleText {
            get {
                return ResourceManager.GetString("hostLeftTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How to Play?.
        /// </summary>
        public static string howToPlayText {
            get {
                return ResourceManager.GetString("howToPlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The match code is incorrect..
        /// </summary>
        public static string incorrectCodeText {
            get {
                return ResourceManager.GetString("incorrectCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string informationText {
            get {
                return ResourceManager.GetString("informationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internal Error.
        /// </summary>
        public static string internalErrorTitle {
            get {
                return ResourceManager.GetString("internalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The E-mail isn&apos;t valid.
        /// </summary>
        public static string invalidEmailErrorText {
            get {
                return ResourceManager.GetString("invalidEmailErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Link.
        /// </summary>
        public static string invalidLinkTitle {
            get {
                return ResourceManager.GetString("invalidLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation by Mail.
        /// </summary>
        public static string invitationMailText {
            get {
                return ResourceManager.GetString("invitationMailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite your Friends.
        /// </summary>
        public static string inviteYourFriendsText {
            get {
                return ResourceManager.GetString("inviteYourFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a joined.
        /// </summary>
        public static string joinedText {
            get {
                return ResourceManager.GetString("joinedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Failed.
        /// </summary>
        public static string joinFailedTitle {
            get {
                return ResourceManager.GetString("joinFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Game.
        /// </summary>
        public static string joingGameText {
            get {
                return ResourceManager.GetString("joingGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name can only contain letters..
        /// </summary>
        public static string lastNameInvalidCharsText {
            get {
                return ResourceManager.GetString("lastNameInvalidCharsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        public static string lastNameText {
            get {
                return ResourceManager.GetString("lastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name cannot exceed 80 characters..
        /// </summary>
        public static string lastNameTooLongText {
            get {
                return ResourceManager.GetString("lastNameTooLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a left.
        /// </summary>
        public static string leftText {
            get {
                return ResourceManager.GetString("leftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not open the link. Make sure you have a web browser installed and set as default..
        /// </summary>
        public static string linkOpenFailText {
            get {
                return ResourceManager.GetString("linkOpenFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The link is not currently available.
        /// </summary>
        public static string linkUnavailableText {
            get {
                return ResourceManager.GetString("linkUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to the server. Please ensure the service is running..
        /// </summary>
        public static string loginConnectionErrorText {
            get {
                return ResourceManager.GetString("loginConnectionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string logInText {
            get {
                return ResourceManager.GetString("logInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error ocurred: {0}.
        /// </summary>
        public static string loginUnexpectedErrorText {
            get {
                return ResourceManager.GetString("loginUnexpectedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome {0} !.
        /// </summary>
        public static string loginWelcomeText {
            get {
                return ResourceManager.GetString("loginWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        public static string logOutText {
            get {
                return ResourceManager.GetString("logOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good luck next time!.
        /// </summary>
        public static string loosersMessageText {
            get {
                return ResourceManager.GetString("loosersMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loosers.
        /// </summary>
        public static string loosersText {
            get {
                return ResourceManager.GetString("loosersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify that both passwords match.
        /// </summary>
        public static string matchingPasswordErrorText {
            get {
                return ResourceManager.GetString("matchingPasswordErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music.
        /// </summary>
        public static string musicText {
            get {
                return ResourceManager.GetString("musicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name can only contain letters..
        /// </summary>
        public static string nameInvalidCharsText {
            get {
                return ResourceManager.GetString("nameInvalidCharsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name.
        /// </summary>
        public static string nameText {
            get {
                return ResourceManager.GetString("nameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Network Error.
        /// </summary>
        public static string networkErrorTitleText {
            get {
                return ResourceManager.GetString("networkErrorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A new code has been sent to your email..
        /// </summary>
        public static string newCodeSentText {
            get {
                return ResourceManager.GetString("newCodeSentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have received a friend request from.
        /// </summary>
        public static string newRequestText {
            get {
                return ResourceManager.GetString("newRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New request.
        /// </summary>
        public static string newRequestTitleText {
            get {
                return ResourceManager.GetString("newRequestTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nextRound.
        /// </summary>
        public static string nextRoundText {
            get {
                return ResourceManager.GetString("nextRoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The nickname may already be in use.
        /// </summary>
        public static string nicknameInUseText {
            get {
                return ResourceManager.GetString("nicknameInUseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname.
        /// </summary>
        public static string nicknameText {
            get {
                return ResourceManager.GetString("nicknameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname cannot exceed 50 characters.
        /// </summary>
        public static string nicknameTooLongText {
            get {
                return ResourceManager.GetString("nicknameTooLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don&apos;t have an Account?.
        /// </summary>
        public static string noAccountText {
            get {
                return ResourceManager.GetString("noAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string noButtonText {
            get {
                return ResourceManager.GetString("noButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have no friends, try to add one.
        /// </summary>
        public static string noFriendsAddOneText {
            get {
                return ResourceManager.GetString("noFriendsAddOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have no pending requests.
        /// </summary>
        public static string noPendingRequestsText {
            get {
                return ResourceManager.GetString("noPendingRequestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to select a player from the connected ones to generate a report.
        /// </summary>
        public static string noSelectedPlayerToReport {
            get {
                return ResourceManager.GetString("noSelectedPlayerToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a of.
        /// </summary>
        public static string ofText {
            get {
                return ResourceManager.GetString("ofText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Was more than one word given as a clue?.
        /// </summary>
        public static string oneMoreWordQuestionText {
            get {
                return ResourceManager.GetString("oneMoreWordQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation Failed.
        /// </summary>
        public static string operationFailedTitleText {
            get {
                return ResourceManager.GetString("operationFailedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pass.
        /// </summary>
        public static string passText {
            get {
                return ResourceManager.GetString("passText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not change the password. Please review the previous error messages..
        /// </summary>
        public static string passwordChangeFailedText {
            get {
                return ResourceManager.GetString("passwordChangeFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The PASSWORD to guess is:.
        /// </summary>
        public static string passwordToGuessText {
            get {
                return ResourceManager.GetString("passwordToGuessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play Again.
        /// </summary>
        public static string playAgainText {
            get {
                return ResourceManager.GetString("playAgainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as guest.
        /// </summary>
        public static string playAsGuestText {
            get {
                return ResourceManager.GetString("playAsGuestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No player was found with that email address.
        /// </summary>
        public static string playerNotFoundText {
            get {
                return ResourceManager.GetString("playerNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players in the room.
        /// </summary>
        public static string playersInTheRoomText {
            get {
                return ResourceManager.GetString("playersInTheRoomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string playersText {
            get {
                return ResourceManager.GetString("playersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string playText {
            get {
                return ResourceManager.GetString("playText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changes saved successfully!.
        /// </summary>
        public static string profileChangesSavedSuccessText {
            get {
                return ResourceManager.GetString("profileChangesSavedSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string profileText {
            get {
                return ResourceManager.GetString("profileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile Updated.
        /// </summary>
        public static string profileUpdatedTitleText {
            get {
                return ResourceManager.GetString("profileUpdatedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reason:.
        /// </summary>
        public static string reasonText {
            get {
                return ResourceManager.GetString("reasonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red Team.
        /// </summary>
        public static string redTeamText {
            get {
                return ResourceManager.GetString("redTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject.
        /// </summary>
        public static string rejectText {
            get {
                return ResourceManager.GetString("rejectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporting to:.
        /// </summary>
        public static string reportingText {
            get {
                return ResourceManager.GetString("reportingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report submitted.
        /// </summary>
        public static string reportSummitedText {
            get {
                return ResourceManager.GetString("reportSummitedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your friend request has been sent.
        /// </summary>
        public static string requestSentText {
            get {
                return ResourceManager.GetString("requestSentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request sent.
        /// </summary>
        public static string requestSentTitleText {
            get {
                return ResourceManager.GetString("requestSentTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter your email and password.
        /// </summary>
        public static string requiredEmailAndPassWordText {
            get {
                return ResourceManager.GetString("requiredEmailAndPassWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please complete the required fields.
        /// </summary>
        public static string requiredFieldsText {
            get {
                return ResourceManager.GetString("requiredFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retrieve Password.
        /// </summary>
        public static string retrieveUserPasswordText {
            get {
                return ResourceManager.GetString("retrieveUserPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The room is full..
        /// </summary>
        public static string roomFullText {
            get {
                return ResourceManager.GetString("roomFullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Round Validation.
        /// </summary>
        public static string roundValidationText {
            get {
                return ResourceManager.GetString("roundValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Each game will consist of two teams of two members.
        ///The teams will be made up of a &quot;Clue Guy,&quot; who will be the player who will see the current password and will be responsible for giving one word per turn as a clue, and a &quot;Guesser,&quot; who will be responsible for guessing the secret word based on the clues given by the other player.
        ///Each game will consist of five rounds of one minute each, with five passwords that the &quot;Guesser&quot; will have to guess.
        ///Each password correctly guessed will be worth one point for  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string rulesGameText {
            get {
                return ResourceManager.GetString("rulesGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        public static string saveChangesText {
            get {
                return ResourceManager.GetString("saveChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score.
        /// </summary>
        public static string scoreTopText {
            get {
                return ResourceManager.GetString("scoreTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose an Avatar.
        /// </summary>
        public static string selectAvatarText {
            get {
                return ResourceManager.GetString("selectAvatarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a profile picture.
        /// </summary>
        public static string selectProfilePictureText {
            get {
                return ResourceManager.GetString("selectProfilePictureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        public static string selectText {
            get {
                return ResourceManager.GetString("selectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Code.
        /// </summary>
        public static string sendCodeText {
            get {
                return ResourceManager.GetString("sendCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Failed.
        /// </summary>
        public static string sendFailedTitleText {
            get {
                return ResourceManager.GetString("sendFailedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Friend Request.
        /// </summary>
        public static string sendFriendRequestText {
            get {
                return ResourceManager.GetString("sendFriendRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Invitation.
        /// </summary>
        public static string sendInvitationText {
            get {
                return ResourceManager.GetString("sendInvitationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string sendText {
            get {
                return ResourceManager.GetString("sendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A communication error with the server occurred..
        /// </summary>
        public static string serverCommunicationErrorText {
            get {
                return ResourceManager.GetString("serverCommunicationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to the server. Check your internet connection or try again later..
        /// </summary>
        public static string serverConnectionInternetErrorText {
            get {
                return ResourceManager.GetString("serverConnectionInternetErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The server took too long to respond. Please try again..
        /// </summary>
        public static string serverTimeoutText {
            get {
                return ResourceManager.GetString("serverTimeoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string settingsText {
            get {
                return ResourceManager.GetString("settingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error registering user. Please try again later.
        /// </summary>
        public static string signUpErrorText {
            get {
                return ResourceManager.GetString("signUpErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string signUpText {
            get {
                return ResourceManager.GetString("signUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Were synonyms used?.
        /// </summary>
        public static string sinonymsQuestionText {
            get {
                return ResourceManager.GetString("sinonymsQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social Media.
        /// </summary>
        public static string socialMediaText {
            get {
                return ResourceManager.GetString("socialMediaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound Effects.
        /// </summary>
        public static string soundEffectsText {
            get {
                return ResourceManager.GetString("soundEffectsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Game.
        /// </summary>
        public static string startGameText {
            get {
                return ResourceManager.GetString("startGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful change.
        /// </summary>
        public static string succesfulPasswordChangeTitleText {
            get {
                return ResourceManager.GetString("succesfulPasswordChangeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend successfully deleted.
        /// </summary>
        public static string successDeletionText {
            get {
                return ResourceManager.GetString("successDeletionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful Login.
        /// </summary>
        public static string successfulLoginText {
            get {
                return ResourceManager.GetString("successfulLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password successfully changed. You will now be redirected to the login page..
        /// </summary>
        public static string successfulPasswordChangeText {
            get {
                return ResourceManager.GetString("successfulPasswordChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful PASSWORDS:.
        /// </summary>
        public static string successfulPasswordsText {
            get {
                return ResourceManager.GetString("successfulPasswordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration Successful.
        /// </summary>
        public static string successfulSignUpText {
            get {
                return ResourceManager.GetString("successfulSignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successful.
        /// </summary>
        public static string successTitleText {
            get {
                return ResourceManager.GetString("successTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Error.
        /// </summary>
        public static string systemErrorTitle {
            get {
                return ResourceManager.GetString("systemErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score: {0}.
        /// </summary>
        public static string teamPointsText {
            get {
                return ResourceManager.GetString("teamPointsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a By Signing Up you Agree to our Terms &amp; Conditions.
        /// </summary>
        public static string termsAndConditionsText {
            get {
                return ResourceManager.GetString("termsAndConditionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The terms and conditions link is not available..
        /// </summary>
        public static string termsLinkUnavailableText {
            get {
                return ResourceManager.GetString("termsLinkUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for your report!.
        /// </summary>
        public static string thanksForReportText {
            get {
                return ResourceManager.GetString("thanksForReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time Limit.
        /// </summary>
        public static string timeLimitTitleText {
            get {
                return ResourceManager.GetString("timeLimitTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Players.
        /// </summary>
        public static string topPlayersText {
            get {
                return ResourceManager.GetString("topPlayersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type your New Password.
        /// </summary>
        public static string typePasswordText {
            get {
                return ResourceManager.GetString("typePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred..
        /// </summary>
        public static string unexpectedErrorText {
            get {
                return ResourceManager.GetString("unexpectedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred while trying to open the link..
        /// </summary>
        public static string unexpectedLinkOpenErrorText {
            get {
                return ResourceManager.GetString("unexpectedLinkOpenErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected server error occurred..
        /// </summary>
        public static string unexpectedServerErrorText {
            get {
                return ResourceManager.GetString("unexpectedServerErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown Error.
        /// </summary>
        public static string unknownErrorTitle {
            get {
                return ResourceManager.GetString("unknownErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have unsaved changes. Are you sure you want to leave and discard them?.
        /// </summary>
        public static string unsavedChangesWarningText {
            get {
                return ResourceManager.GetString("unsavedChangesWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discard Changes.
        /// </summary>
        public static string unsavedChangesWarningTitleText {
            get {
                return ResourceManager.GetString("unsavedChangesWarningTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User already exist with that e-mail.
        /// </summary>
        public static string userAlreadyExistText {
            get {
                return ResourceManager.GetString("userAlreadyExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use 8-15 characters including at least one uppercase, one lowercase, one numeric character and one symbol.
        /// </summary>
        public static string userPasswordRequirementsText {
            get {
                return ResourceManager.GetString("userPasswordRequirementsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string userPasswordText {
            get {
                return ResourceManager.GetString("userPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate Round.
        /// </summary>
        public static string validateRoundText {
            get {
                return ResourceManager.GetString("validateRoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification Failed.
        /// </summary>
        public static string verificationFailedTitleText {
            get {
                return ResourceManager.GetString("verificationFailedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type the 6 digit code sent to the e-mail:.
        /// </summary>
        public static string verifyCodeMessageText {
            get {
                return ResourceManager.GetString("verifyCodeMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Didn&apos;t receive the code?.
        /// </summary>
        public static string verifyCodeNotSendText {
            get {
                return ResourceManager.GetString("verifyCodeNotSendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend Code.
        /// </summary>
        public static string verifyCodeResendCodeText {
            get {
                return ResourceManager.GetString("verifyCodeResendCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Code.
        /// </summary>
        public static string verifyCodeText {
            get {
                return ResourceManager.GetString("verifyCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please wait at least one minute before requesting another code..
        /// </summary>
        public static string waitAMinuteForCodeText {
            get {
                return ResourceManager.GetString("waitAMinuteForCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string warningTitleText {
            get {
                return ResourceManager.GetString("warningTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Congratulations you won PASSWORD.
        /// </summary>
        public static string winnersMessageText {
            get {
                return ResourceManager.GetString("winnersMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Winners.
        /// </summary>
        public static string winnersText {
            get {
                return ResourceManager.GetString("winnersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write a clue for your teammate:.
        /// </summary>
        public static string writeClueText {
            get {
                return ResourceManager.GetString("writeClueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your friend&apos;s email address to invite:.
        /// </summary>
        public static string writeEmailToInviteText {
            get {
                return ResourceManager.GetString("writeEmailToInviteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the PASSWORD that you think is.
        /// </summary>
        public static string writePasswordText {
            get {
                return ResourceManager.GetString("writePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect e-mail or password.
        /// </summary>
        public static string wrongCredentialsText {
            get {
                return ResourceManager.GetString("wrongCredentialsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string yesButtonText {
            get {
                return ResourceManager.GetString("yesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;re already in the game..
        /// </summary>
        public static string youAreAlreadyInGameText {
            get {
                return ResourceManager.GetString("youAreAlreadyInGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been reported by.
        /// </summary>
        public static string youHaveBeenReportedByText {
            get {
                return ResourceManager.GetString("youHaveBeenReportedByText", resourceCulture);
            }
        }
    }
}
